USE [master]
GO

/****** Object:  Database [AdvsDiag]    Script Date: 11/28/2017 16:19:18 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'AdvsDiag')
DROP DATABASE [AdvsDiag]
GO

USE [master]
GO

/****** Object:  Database [AdvsDiag]    Script Date: 11/28/2017 16:19:18 ******/
CREATE DATABASE [AdvsDiag] ON  PRIMARY 
( NAME = N'AdvsDiag', FILENAME = N'E:\SQLData\AdvsDiag.mdf' , SIZE = 26944KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'AdvsDiag_log', FILENAME = N'E:\SQLLogs\AdvsDiag_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AdvsDiag] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdvsDiag].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdvsDiag] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AdvsDiag] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AdvsDiag] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AdvsDiag] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AdvsDiag] SET ARITHABORT OFF 
GO

ALTER DATABASE [AdvsDiag] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AdvsDiag] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AdvsDiag] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AdvsDiag] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AdvsDiag] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AdvsDiag] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AdvsDiag] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AdvsDiag] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AdvsDiag] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AdvsDiag] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AdvsDiag] SET  ENABLE_BROKER 
GO

ALTER DATABASE [AdvsDiag] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AdvsDiag] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AdvsDiag] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AdvsDiag] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AdvsDiag] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AdvsDiag] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AdvsDiag] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AdvsDiag] SET  READ_WRITE 
GO

ALTER DATABASE [AdvsDiag] SET RECOVERY FULL 
GO

ALTER DATABASE [AdvsDiag] SET  MULTI_USER 
GO

ALTER DATABASE [AdvsDiag] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AdvsDiag] SET DB_CHAINING OFF 
GO


